---
- project:
    name: openstack-k8s-operators/watcher-operator
    default-branch: main
    github-check:
      jobs:
        - openstack-meta-content-provider:
            vars:
              cifmw_operator_build_meta_build: false
        - watcher-operator-validation

- job:
    name: watcher-operator-base
    parent: podified-multinode-edpm-deployment-crc-2comp
    dependencies: ["openstack-meta-content-provider"]
    description: |
      A multinode EDPM Zuul job which has one ansible controller, one
      extracted crc and two computes. It will be used for testing watcher-operator.
    vars:
      watcher_repo: "{{ ansible_user_dir }}/src/github.com/openstack-k8s-operators/watcher-operator"
      watcher_hook: "{{ watcher_repo }}/ci/playbooks/deploy_watcher_service.yaml"
      cifmw_install_yamls_whitelisted_vars:
        - 'WATCHER_REPO'
        - 'WATCHER_BRANCH'
        - 'OUTPUT_DIR'
      post_deploy:
        - name: Deploy watcher service
          type: playbook
          source: "{{ watcher_hook }}"
          extra_vars:
            watcher_catalog_image: "{{ content_provider_registry_ip }}:5001/openstack-k8s-operators/watcher-operator-index:{{ zuul.patchset }}"

- job:
    name: watcher-operator-validation
    parent: watcher-operator-base
    description: |
      A zuul job to validate the watcher operator and its service deployment.
    vars:
      run_tempest: false
