---
# This hook is used to deploy watcher service.

- name: Deploy Watcher service
  hosts: "{{ cifmw_target_hook_host | default('localhost') }}"
  gather_facts: false
  environment:
    KUBECONFIG: "{{ cifmw_openshift_kubeconfig }}"
    PATH: "{{ cifmw_path }}"
  tasks:
    - name: Fetch dlrn md5_hash from master DLRN repo
      when: fetch_master_dlrn_hash | default(true) | bool
      ansible.builtin.uri:
        url: "https://{{ watcher_dlrn_server | default('trunk.rdoproject.org') }}/{{ watcher_dlrn_namespace | default('centos9-master') }}/{{ watcher_dlrn_tag | default('current-podified') }}/delorean.repo.md5"
        return_content: true
      register: latest_dlrn_tag
      until: latest_dlrn_tag.status == 200
      retries: 6
      delay: 5

    - name: Install Watcher Operator
      vars:
        _tag: "{{ latest_dlrn_tag.content | default('current-podified') }}"
        _registry_url: "{{ content_provider_os_registry_url | default('quay.io/podified-master-centos9') }}"
      cifmw.general.ci_script:
        output_dir: "{{ cifmw_basedir }}/artifacts"
        chdir: "{{ ansible_user_dir }}/src/github.com/openstack-k8s-operators/watcher-operator"
        script: make watcher
        extra_args:
          CATALOG_IMAGE: "{{ watcher_catalog_image | default('quay.io/openstack-k8s-operators/watcher-operator-index:latest') }}"
          WATCHER_API_IMAGE_URL_DEFAULT: "{{ content_provider_os_registry_url }}/openstack-watcher-api:{{ _tag }}"
          WATCHER_DECISION_ENGINE_IMAGE_URL_DEFAULT: "{{ content_provider_os_registry_url }}/openstack-watcher-decision-engine:{{ _tag }}"
          WATCHER_APPLIER_IMAGE_URL_DEFAULT: "{{ content_provider_os_registry_url }}/openstack-watcher-applier:{{ _tag }}"

    - name: Deploy Watcher service
      when: deploy_watcher_service | default('true') | bool
      cifmw.general.ci_script:
        output_dir: "{{ cifmw_basedir }}/artifacts"
        chdir: "{{ ansible_user_dir }}/src/github.com/openstack-k8s-operators/watcher-operator"
        script: make watcher_deploy
