# permissions for end users to view watcherapis.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: watcher-operator
    app.kubernetes.io/managed-by: kustomize
  name: watcherapi-viewer-role
rules:
- apiGroups:
  - watcher.openstack.org
  resources:
  - watcherapis
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - watcher.openstack.org
  resources:
  - watcherapis/status
  verbs:
  - get
