apiVersion: watcher.openstack.org/v1beta1
kind: WatcherAPI
metadata:
  labels:
    app.kubernetes.io/name: watcher-operator
    app.kubernetes.io/managed-by: kustomize
  name: watcherapi-sample
spec:
  databaseInstance: "openstack"
  secret: "osp-secret"
