apiVersion: watcher.openstack.org/v1beta1
kind: WatcherAPI
metadata:
  labels:
    app.kubernetes.io/name: watcher-operator
    app.kubernetes.io/managed-by: kustomize
  name: watcherapi-sample
spec:
  secret: "watcher"
  memcachedInstance: "memcached"
  # jgilaber this field should be removed once we create the WatcherAPI from
  # the Watcher controller
  containerImage: "quay.io/podified-antelope-centos9/openstack-watcher-api:current-podified"
  serviceAccount: "watcher-watcher"
