name: Build Docs
on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    paths:
      - .github/workflows/docs*
      - docs/**
      - Gemfile
jobs:
  deploy:
    if: github.repository == 'openstack-k8s-operators/watcher-operator'
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.21.x
      - uses: actions/checkout@v4
        with:
          # this fetches all branches. Needed because we need gh-pages branch for deploy to work
          fetch-depth: 0
      - uses: ruby/setup-ruby@v1.160.0
        with:
          ruby-version: '3.2'

      - name: Build docs
        run: |
          make docs
          cp docs_build/watcher-operator/index.html index.html

      - name: Prepare gh-pages branch
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com

          git branch -D gh-pages &>/dev/null || true
          git checkout --orphan gh-pages
          git reset

      - name: Commit asciidoc docs
        run: |
          git add index.html
          git commit -m "Rendered docs"

      - name: Push rendered docs to gh-pages
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: |
          git push --force origin gh-pages
